{
 "title": "Metallb",
 "description": "Metallb key metrics",
 "tags": [
  "metallb ",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bgpinstance",
    "label": "BGP instance",
    "query": {
     "query": "label_values(metallb_bgp_session_up,instance)"
    }
   },
   {
    "name": "bgppeer",
    "label": "BGP Peer IP",
    "query": {
     "query": "label_values(metallb_bgp_session_up,peer)"
    }
   },
   {
    "name": "layer2instance",
    "label": "Layer 2 instance",
    "query": {
     "query": "label_values(metallb_layer2_gratuitous_sent,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Address utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metallb_allocator_addresses_total",
     "legendFormat": "IP Pool Size in "
    },
    {
     "expr": "metallb_allocator_addresses_in_use_total",
     "legendFormat": "IP Pool Allocation in "
    }
   ]
  },
  {
   "title": "IP Pool Usuage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((metallb_allocator_addresses_in_use_total / metallb_allocator_addresses_total)) by (pool) / count(metallb_allocator_addresses_in_use_total) by (pool) * 100)",
     "legendFormat": "Utilisation for IP Pool "
    }
   ]
  },
  {
   "title": "BGP Prefixes Advertised",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metallb_bgp_announced_prefixes_total{peer=~\"$bgppeer\"}[$__range]"
    }
   ]
  },
  {
   "title": "Stale config",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(metallb_k8s_client_config_stale_bool)",
     "legendFormat": "client_config_stale"
    }
   ]
  },
  {
   "title": "Layer 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(metallb_layer2_gratuitous_sent{instance=~\"$layer2instance\"}[$__range])",
     "legendFormat": "gratuitous_sent instance= ip= "
    },
    {
     "expr": "rate(metallb_layer2_requests_received{instance=~\"$layer2instance\"}[$__range])",
     "legendFormat": "requests_received instance= ip= "
    },
    {
     "expr": "rate(metallb_layer2_responses_sent{instance=~\"$layer2instance\"}[$__range])",
     "legendFormat": "responses_sent instance= ip= "
    }
   ]
  },
  {
   "title": "Client updates",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(metallb_k8s_client_update_errors_total[$__range])",
     "legendFormat": "Error updates via  on "
    },
    {
     "expr": "rate(metallb_k8s_client_updates_total[$__range])",
     "legendFormat": "Total Updates via  on "
    }
   ]
  }
 ]
}